tags:
  kafka: true
  cockroach: true
  backup: false

kafkaTopics: []

# kafkabrokers: &kb "kafka-headless.default.svc.cluster.local:29092"
# chatTopic: &topic "vlab-test-chat-events"
# botEnvs: &botenvs gbv-bot-envs
# chatbaseHost: &host "gbv-cockroachdb-public"

versionDashboard: &vdashboard 0.0.5
versionNaughtybot: &vnaughtybot 0.0.12
versionBotserver: &vbotserver 0.0.6
versionReplybot: &vreplybot 0.0.66
versionBotscribe: &vbotscribe 0.0.6

naughtybot:
  image:
    repository: vlabresearch/naughtybot
    tag: *vnaughtybot
    pullPolicy: IfNotPresent

  env:
  - name: CHATBASE_BACKEND
    value: "@vlab-research/chatbase-postgres"
  - name: CHATBASE_DATABASE
    value: "chatroach"
  - name: CHATBASE_USER
    value: "chatroach"
  - name: CHATBASE_PASSWORD
    value: ""
  - name: CHATBASE_HOST
    value: "gbv-cockroachdb-public.default"
  - name: CHATBASE_PORT
    value: "26257"
  - name: BOTSPINE_KAFKA_BROKERS
    value: "gbv-kafka:9092"
  - name: BOTSPINE_MESSAGE_TOPIC
    value: "chat-events"
  - name: BOTSERVER_URL
    value: "http://gbv-botserver"

  writer:
    replicaCount: 1
    resources:
      requests:
        cpu: 10m
        memory: 64Mi

  dean:
    schedule: "*/1 * * * *"
    resources:
      requests:
        cpu: 10m
        memory: 64Mi


linksniffer:
  replicaCount: 1

  image:
    repository: vlabresearch/linksniffer
    tag: 0.0.2
    pullPolicy: IfNotPresent

  env:
  - name: BOTSERVER_URL
    value: "http://gbv-botserver"
  - name: FB_PAGE_ID
    value: "935593143497601"

  resources:
    requests:
      cpu: 10m
      memory: 50Mi

  ingress:
    enabled: false

  service:
    type: ClusterIP
    port: 80

dashboard:
  replicaCount: 1

  image:
    repository: vlabresearch/dashboard
    tag: *vdashboard
    pullPolicy: IfNotPresent

  envFrom: gbv-bot-envs
  env:
    - name: TYPEFORM_URL
      value: 'https://api.typeform.com'
    - name: CUBEJS_API_SECRET
      value: 'notasecret'
    - name: CUBEJS_DB_TYPE
      value: 'postgres'
    - name: DB_DATABASE
      value: 'chatroach'
    - name: CUBEJS_DB_NAME
      value: 'chatroach'
    - name: DB_USER
      value: 'chatroach'
    - name: CUBEJS_DB_USER
      value: 'chatroach'
    - name: DB_PASSWORD
      value: ''
    - name: CUBEJS_DB_PASS
      value: ''
    - name: DB_HOST
      value: 'gbv-cockroachdb-public.default'
    - name: CUBEJS_DB_HOST
      value: 'gbv-cockroachdb-public.default'
    - name: DB_PORT
      value: '26257'
    - name: CUBEJS_DB_PORT
      value: '26257'
    - name: TYPEFORM_REDIRECT_URL
      value: 'http://localhost:3000/surveys/auth'

  resources:
    requests:
      cpu: 10m
      memory: 64Mi

  ingress:
    enabled: false

  service:
    type: ClusterIP
    port: 80



scratchbot:
  replicaCount: 1

  image:
    repository: vlabresearch/replybot
    tag: *vreplybot
    pullPolicy: IfNotPresent

  envFrom: gbv-bot-envs

  env:
  - name: CHATBASE_BACKEND
    value: "@vlab-research/chatbase-postgres"
  - name: CHATBASE_DATABASE
    value: "chatroach"
  - name: CHATBASE_USER
    value: "chatroach"
  - name: CHATBASE_PASSWORD
    value: ""
  - name: CHATBASE_HOST
    value: "gbv-cockroachdb-public.default"
  - name: CHATBASE_PORT
    value: "26257"
  - name: FALLBACK_FORM
    value: "305"
  - name: REPLYBOT_EVENT_TOPIC
    value: "chat-events"
  - name: BOTSPINE_KAFKA_BROKERS
    value: "gbv-kafka:9092"
  - name: BOTSPINE_MESSAGE_TOPIC
    value: "chat-events"
  - name: DASHBOARD_API
    value: "http://gbv-dashboard/api/v1"

  resources:
    requests:
      cpu: 10m
      memory: 64Mi



botscribe:
  replicaCount: 1

  image:
    repository: vlabresearch/botscribe
    tag: *vbotscribe
    pullPolicy: IfNotPresent

  envFrom: gbv-bot-envs

  env:
  - name: CHATBASE_BACKEND
    value: "@vlab-research/chatbase-postgres"
  - name: CHATBASE_DATABASE
    value: "chatroach"
  - name: CHATBASE_USER
    value: "chatroach"
  - name: CHATBASE_PASSWORD
    value: ""
  - name: CHATBASE_HOST
    value: "gbv-cockroachdb-public.default"
  - name: CHATBASE_PORT
    value: "26257"
  - name: BOTSCRIBE_HIGHWATER
    value: "500"
  - name: BOTSPINE_KAFKA_BROKERS
    value: "gbv-kafka:9092"
  - name: BOTSPINE_MESSAGE_TOPIC
    value: "chat-events"

  resources:
    requests:
      cpu: 10m
      memory: 64Mi


replybot:
  replicaCount: 1
  image:
    repository: vlabresearch/replybot
    tag: *vreplybot
    pullPolicy: IfNotPresent

  envFrom: gbv-bot-envs
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
  env:
  - name: CHATBASE_BACKEND
    value: "@vlab-research/chatbase-postgres"
  - name: CHATBASE_DATABASE
    value: "chatroach"
  - name: CHATBASE_USER
    value: "chatroach"
  - name: CHATBASE_PASSWORD
    value: ""
  - name: CHATBASE_HOST
    value: "gbv-cockroachdb-public.default"
  - name: CHATBASE_PORT
    value: "26257"
  - name: FALLBACK_FORM
    value: "305"
  - name: REPLYBOT_EVENT_TOPIC
    value: "chat-events"
  - name: FACEBOOK_GRAPH_URL
    value: "http://gbv-facebot"
  - name: BOTSPINE_KAFKA_BROKERS
    value: "gbv-kafka:9092"
  - name: BOTSPINE_MESSAGE_TOPIC
    value: "chat-events"
  - name: DASHBOARD_API
    value: "http://gbv-dashboard/api/v1"
  - name: BOTSERVER_URL
    value: "http://gbv-botserver"


botserver:
  replicaCount: 1

  image:
    repository: vlabresearch/botserver
    tag: *vbotserver
    pullPolicy: IfNotPresent

  envFrom: gbv-bot-envs

  env:
  - name: BOTSERVER_EVENT_TOPIC
    value: "chat-events"
  - name: KAFKA_BROKERS
    value: "gbv-kafka:9092"

  resources:
    requests:
      cpu: 10m
      memory: 64Mi

  ingress:
    enabled: false


  service:
    type: ClusterIP
    port: 80


cockroachdb:
  statefulset:
    replicas: 1
  conf:
    budget:
      maxUnavailable: 0
  tls:
    enabled: no
  resources:
    requests:
      cpu: 25m
      memory: 256Mi
  storage:
    persistentVolume:
      size: 1Gi


kafka:
  replicas: 1
  imageTag: 5.4.0
  resources:
    requests:
      cpu: 25m
      memory: 200Mi
  zookeeper:
    resources:
      requests:
        cpu: 5m
        memory: 50Mi
  kafkaHeapOptions: "-Xmx500M -Xms500M"
  configurationOverrides:
    "offsets.topic.replication.factor": 1
    "auto.create.topics.enable": false
  topics:
    - name: "chat-events"
      config: "retention.ms=1209600000" # 14 days
      partitions: 6
      replicationFactor: 1
  persistence:
    size: 1Gi
    storageClass: "microk8s-hostpath"
